TrainingArguments:
  num_train_epochs : 10
  learning_rate : 0.00005
  per_device_train_batch_size : 64
  per_device_eval_batch_size : 64
  weight_decay : 0.01
  evaluation_strategy : "epoch"
  disable_tqdm : False
  logging_steps : 1000
  log_level : "error"
