artifacts_root: artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL: https://github.com/akash-sardar/datasets/raw/396131e6296d74426146965dd66c3e0462bd5158/banking77/banking77.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir : artifacts/data_validation
  STATUS_FILE : artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES : ["train.csv", "test.csv", "categories.json"]

data_transformation:
  root_dir : artifacts/data_transformation
  data_path : artifacts/data_ingestion
  tokenizer_name : distilbert-base-uncased

model_trainer:
  root_dir: artifacts/model_trainer
  data_path : artifacts/data_transformation
  model_ckpt : distilbert-base-uncased

model_evaluation:
  root_dir : artifacts/model_evaluation
  transformed_data_path : artifacts/data_transformation
  data_path : artifacts/data_ingestion
  model_path : artifacts/model_trainer/distilbert-base-uncased-finetuned-banking77
  tokenizer_path : artifacts/model_trainer/tokenizer-finetuned-banking77
  metric_file_name : artifacts/model_evaluation/metrics.csv
